# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ubuntu server image
IMAGE_NAME = "generic/ubuntu2004" 

# Number of Ubuntu servers to spin up
N_MACHINES = 1


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = false
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.provider "libvirt" do |v|
        v.memory = 4096
        v.cpus = 4
        v.management_network_name = 'vagrant-libvirt-custom'
        v.management_network_address = '192.168.124.0/24'
    end

    (1..N_MACHINES).each do |i|
        config.vm.define "server-#{i}" do |ubuntu|
            ubuntu.vm.box = IMAGE_NAME
                
            # Create a private network, which allows host-only access to the machine
            # using a specific IP.
            ubuntu.vm.network "private_network", ip: "192.168.10.#{i + 9}"
                

            # Create a public network, which generally matched to bridged network.
            # Bridged networks make the machine appear as another physical device on
            # your network. To give a static ip, add ip: "192.168.X.X" to the following
            #config.vm.network :public_network, :bridge => 'eth0', :dev => 'eth0' 
            
            # Port forwarding
            # config.vm.network "forwarded_port", guest: 80, host: 8080

            ubuntu.vm.hostname = "server-#{i}"

        end
    end

end
