# -*- mode: ruby -*-
# vi: set ft=ruby :


# Ubuntu server image
IMAGE_NAME = "generic/ubuntu2004" 

# number of workers nodes in production namespace (should be at maximum 9)
N_PROD = 3

# number of workers nodes in development namespace (should be at maximum 9)
N_DEV = 3

# Run with noparallel by default
ENV['VAGRANT_NO_PARALLEL'] = 'yes'


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
        v.gui = false
    end

    config.vm.provider "libvirt" do |v|
        v.nested = true
        v.cpu_mode = "host-model"
        v.memory = 8192
        v.cpus = 4
        v.management_network_name = 'vagrant-libvirt-custom'
        v.management_network_address = '10.50.50.0/24'
    end
    
    config.vm.define "k8s-master-dev" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.16.3.10"
        master.vm.hostname = "k8s-master-dev"
        master.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "ansible-playbooks/master-playbook-dev.yml"
            ansible.extra_vars = {
                node_ip: "172.16.3.10",
                ansible_python_interpreter:"/usr/bin/python3"
            }
        end
    end

    (1..N_DEV).each do |i|
        config.vm.define "node-dev-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "172.16.3.#{i + 10}"
            node.vm.hostname = "node-dev-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "ansible-playbooks/node-playbook-dev.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.3.#{i + 10}",
                    ansible_python_interpreter:"/usr/bin/python3"
                }
            end
        end
    end

    config.vm.define "k8s-master-prod" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.16.4.10"
        master.vm.hostname = "k8s-master-prod"
        master.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "ansible-playbooks/master-playbook-prod.yml"
            ansible.extra_vars = {
                node_ip: "172.16.4.10",
                ansible_python_interpreter:"/usr/bin/python3"
            }
        end
    end

    (1..N_PROD).each do |i|
        config.vm.define "node-prod-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "172.16.4.#{i + 10}"
            node.vm.hostname = "node-prod-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "ansible-playbooks/node-playbook-prod.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.4.#{i + 10}",
                    ansible_python_interpreter:"/usr/bin/python3"
                }
            end
        end
    end
end