# -*- mode: ruby -*-
# vi: set ft=ruby :


# Ubuntu server image
IMAGE_NAME = "generic/ubuntu2004" 

# number of workers nodes (should be at maximum 9)
N_W_NODES = 2

# number of master nodes 
N_M_NODES = 2

# Run with noparallel by default
ENV['VAGRANT_NO_PARALLEL'] = 'yes'


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.gui = false
    end

    config.vm.provider "libvirt" do |v|
        v.nested = true
        v.cpu_mode = "host-model"
        v.memory = 2048
        v.cpus = 2
        v.management_network_name = 'vagrant-libvirt-custom'
        v.management_network_address = '10.50.50.0/24'
    end
    
    (1..N_M_NODES).each do |i|
        config.vm.define "k8s-master" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "172.16.3.10"
            master.vm.hostname = "k8s-master"
            master.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "ansible-playbooks/master-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.3.10",
                    ansible_python_interpreter:"/usr/bin/python3"
                }
            end
        end
    end

    (1..N_W_NODES).each do |i|
        config.vm.define "worker-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "172.16.3.#{i + 10}"
            node.vm.hostname = "worker-node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "ansible-playbooks/worker-node.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.3.#{i + 10}",
                    ansible_python_interpreter:"/usr/bin/python3"
                }
            end
        end
    end

end